changelog:
  categories:
    - title: New features
      labels: [enhancement]
    - title: Fixes
      labels: [bug]
    - title: Maintenance
      labels: [documentation, maintenance]
    - title: Other changes
      labels: ["*"]
